import { Outfit } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";


const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Cafe de Altura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={outfit.className}>
        


      <div className='flex h-screen'>
      <Sidebar />
      <div className='flex-1 p-4'>
        {children}
      </div>
    </div>

        </body>
    </html>
  );
}
