import { Outfit } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar.jsx";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Examen Final",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={outfit.className}>
        <div className="layout">
          <Sidebar />
          <main className="content">{children}</main>
        </div>
      </body>
    </html>
  );
}